name: Update Readme

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Update Readme
        run: node update-readme.js
       # env:
        #  IMAGES: <p align="center"><img align="center" src="https://img.shields.io/github/contributors/${{ github.repository }}"> <img align="center" src="https://img.shields.io/github/issues/${{ github.repository }}"> <img align="center" src="https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=shields"> <img align="center" src="https://img.shields.io/github/issues-pr/${{ github.repository }}"> <a href="https://github.com/${{ github.repository }}/blob/master/LICENSE"><img align="center" src="https://img.shields.io/badge/License-MIT-yellow.svg"></a><img align="center" src="https://img.shields.io/github/commit-activity/m/${{ github.repository }}"> <img align="center" src="https://github.com/Julius-Ulee/github-profile-views-counter/blob/master/svg/738176371/badge.svg"> <img align="center" src="https://github.com/Julius-Ulee/github-profile-views-counter/blob/master/graph/738176371/small/week.png"><br><img align="center" src="https://img.shields.io/maintenance/yes/2024"></p>
        #  BADGES: <p align="center"><b>Display GitHub Action Badge</b> <a href="https://github.com/${{ github.repository }}/actions/workflows/black.yml"><img align="center" src="https://github.com/${{ github.repository }}/actions/workflows/black.yml/badge.svg"></a> <a href="https://github.com/${{ github.repository }}/actions/workflows/jekyll.yml"><img align="center" src="https://github.com/${{ github.repository }}/actions/workflows/jekyll.yml/badge.svg"></a></p>
        #  INFO: <p align="center"><a href="https://github.com/${{ github.repository }}/blob/master/README.md">Readme</a> • <a href="https://github.com/${{ github.repository }}/blob/master/.github/workflows/black.yml">Actions-YML</a> • <a href="https://github.com/${{ github.repository }}/blob/master/.gitignore">Gitignore</a> • <a href="https://github.com/${{ github.repository }}/blob/master/LICENSE">License</a> • <a href="https://github.com/${{ github.repository }}/blob/master/update-readme.js">Update-readme</a> • <a href="https://github.com/${{ github.repository }}/blob/master/package.json">Package</a></p>

      - name: Configure Git
        run: |
          git config --global user.name "azrielbsi"
          git config --global user.email "19215261@bsi.ac.id"

      - name: Commit and Push changes
        run: |
          git add .
          git commit -m ":octocat: Announcements Anime $(date +'%D %T')"
          git remote set-url origin https://github.com/${{ github.repository }}.git
          git push

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
